# Default values for hotload-integration-tests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: hotload-integration-tests

image:
  repository: hotload-integration-tests
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# postgres configuration using official postgres:10 image
postgres:
  image: postgres:10
  user: admin
  password: test
  database: hldatabase
  postgresPassword: postgres  # password for 'postgres' superuser
  persistence:
    enabled: false
  initScript: |
    CREATE DATABASE hotload_test;
    CREATE DATABASE hotload_test1;
    GRANT ALL PRIVILEGES ON DATABASE hotload_test TO admin;
    GRANT ALL PRIVILEGES ON DATABASE hotload_test1 TO admin;
