// Code generated by internal/gen. DO NOT EDIT.

package hotload

import "database/sql/driver"

// wrapConn wraps b so that the returned driver.Conn exposes an optional
// interface if and only if the underlying conn supports the capability.
// The legacy Execer/Queryer interfaces are collapsed into their context
// flavors: the wrapper only ever exposes ExecerContext/QueryerContext and
// replicates database/sql's legacy fallback internally (see
// baseConn.execContext and baseConn.queryContext).
func connFlags(c driver.Conn) uint8 {
	var f uint8
	if _, ok := c.(driver.ExecerContext); ok {
		f |= 1 << 0
	} else if _, ok := c.(driver.Execer); ok { //nolint:staticcheck // legacy interface intentionally supported
		f |= 1 << 0
	}
	if _, ok := c.(driver.QueryerContext); ok {
		f |= 1 << 1
	} else if _, ok := c.(driver.Queryer); ok { //nolint:staticcheck // legacy interface intentionally supported
		f |= 1 << 1
	}
	if _, ok := c.(driver.Pinger); ok {
		f |= 1 << 2
	}
	if _, ok := c.(driver.NamedValueChecker); ok {
		f |= 1 << 3
	}
	return f
}

type conn_E struct {
	*baseConn
	cExecer
}

var (
	_ driver.Conn          = conn_E{}
	_ driver.ExecerContext = conn_E{}
)

type conn_Q struct {
	*baseConn
	cQueryer
}

var (
	_ driver.Conn           = conn_Q{}
	_ driver.QueryerContext = conn_Q{}
)

type conn_EQ struct {
	*baseConn
	cExecer
	cQueryer
}

var (
	_ driver.Conn           = conn_EQ{}
	_ driver.ExecerContext  = conn_EQ{}
	_ driver.QueryerContext = conn_EQ{}
)

type conn_P struct {
	*baseConn
	cPinger
}

var (
	_ driver.Conn   = conn_P{}
	_ driver.Pinger = conn_P{}
)

type conn_EP struct {
	*baseConn
	cExecer
	cPinger
}

var (
	_ driver.Conn          = conn_EP{}
	_ driver.ExecerContext = conn_EP{}
	_ driver.Pinger        = conn_EP{}
)

type conn_QP struct {
	*baseConn
	cQueryer
	cPinger
}

var (
	_ driver.Conn           = conn_QP{}
	_ driver.QueryerContext = conn_QP{}
	_ driver.Pinger         = conn_QP{}
)

type conn_EQP struct {
	*baseConn
	cExecer
	cQueryer
	cPinger
}

var (
	_ driver.Conn           = conn_EQP{}
	_ driver.ExecerContext  = conn_EQP{}
	_ driver.QueryerContext = conn_EQP{}
	_ driver.Pinger         = conn_EQP{}
)

type conn_N struct {
	*baseConn
	cNVChecker
}

var (
	_ driver.Conn              = conn_N{}
	_ driver.NamedValueChecker = conn_N{}
)

type conn_EN struct {
	*baseConn
	cExecer
	cNVChecker
}

var (
	_ driver.Conn              = conn_EN{}
	_ driver.ExecerContext     = conn_EN{}
	_ driver.NamedValueChecker = conn_EN{}
)

type conn_QN struct {
	*baseConn
	cQueryer
	cNVChecker
}

var (
	_ driver.Conn              = conn_QN{}
	_ driver.QueryerContext    = conn_QN{}
	_ driver.NamedValueChecker = conn_QN{}
)

type conn_EQN struct {
	*baseConn
	cExecer
	cQueryer
	cNVChecker
}

var (
	_ driver.Conn              = conn_EQN{}
	_ driver.ExecerContext     = conn_EQN{}
	_ driver.QueryerContext    = conn_EQN{}
	_ driver.NamedValueChecker = conn_EQN{}
)

type conn_PN struct {
	*baseConn
	cPinger
	cNVChecker
}

var (
	_ driver.Conn              = conn_PN{}
	_ driver.Pinger            = conn_PN{}
	_ driver.NamedValueChecker = conn_PN{}
)

type conn_EPN struct {
	*baseConn
	cExecer
	cPinger
	cNVChecker
}

var (
	_ driver.Conn              = conn_EPN{}
	_ driver.ExecerContext     = conn_EPN{}
	_ driver.Pinger            = conn_EPN{}
	_ driver.NamedValueChecker = conn_EPN{}
)

type conn_QPN struct {
	*baseConn
	cQueryer
	cPinger
	cNVChecker
}

var (
	_ driver.Conn              = conn_QPN{}
	_ driver.QueryerContext    = conn_QPN{}
	_ driver.Pinger            = conn_QPN{}
	_ driver.NamedValueChecker = conn_QPN{}
)

type conn_EQPN struct {
	*baseConn
	cExecer
	cQueryer
	cPinger
	cNVChecker
}

var (
	_ driver.Conn              = conn_EQPN{}
	_ driver.ExecerContext     = conn_EQPN{}
	_ driver.QueryerContext    = conn_EQPN{}
	_ driver.Pinger            = conn_EQPN{}
	_ driver.NamedValueChecker = conn_EQPN{}
)

func wrapConn(b *baseConn) driver.Conn {
	switch connFlags(b.inner) {
	case 1:
		return conn_E{b, cExecer{b}}
	case 2:
		return conn_Q{b, cQueryer{b}}
	case 3:
		return conn_EQ{b, cExecer{b}, cQueryer{b}}
	case 4:
		return conn_P{b, cPinger{b}}
	case 5:
		return conn_EP{b, cExecer{b}, cPinger{b}}
	case 6:
		return conn_QP{b, cQueryer{b}, cPinger{b}}
	case 7:
		return conn_EQP{b, cExecer{b}, cQueryer{b}, cPinger{b}}
	case 8:
		return conn_N{b, cNVChecker{b}}
	case 9:
		return conn_EN{b, cExecer{b}, cNVChecker{b}}
	case 10:
		return conn_QN{b, cQueryer{b}, cNVChecker{b}}
	case 11:
		return conn_EQN{b, cExecer{b}, cQueryer{b}, cNVChecker{b}}
	case 12:
		return conn_PN{b, cPinger{b}, cNVChecker{b}}
	case 13:
		return conn_EPN{b, cExecer{b}, cPinger{b}, cNVChecker{b}}
	case 14:
		return conn_QPN{b, cQueryer{b}, cPinger{b}, cNVChecker{b}}
	case 15:
		return conn_EQPN{b, cExecer{b}, cQueryer{b}, cPinger{b}, cNVChecker{b}}
	default:
		return b
	}
}
