FROM golang:1.20 AS builder
WORKDIR /go/src/github.com/infobloxopen/hotload/
COPY . .

# build integration test binary
RUN make build-test

FROM ubuntu:20.04 AS runner
COPY --from=builder /go/src/github.com/infobloxopen/hotload/integrationtests.test .

