// Code generated by internal/gen. DO NOT EDIT.

package hotload

import "database/sql/driver"

// stmtFlags reports which optional interfaces the wrapped stmt must expose.
func stmtFlags(s driver.Stmt) uint8 {
	var f uint8
	if _, ok := s.(driver.StmtExecContext); ok {
		f |= 1 << 0
	}
	if _, ok := s.(driver.StmtQueryContext); ok {
		f |= 1 << 1
	}
	if _, ok := s.(driver.ColumnConverter); ok { //nolint:staticcheck // legacy interface intentionally supported
		f |= 1 << 2
	}
	if _, ok := s.(driver.NamedValueChecker); ok {
		f |= 1 << 3
	}
	return f
}

type stmt_E struct {
	*baseStmt
	sExecer
}

var (
	_ driver.Stmt            = stmt_E{}
	_ driver.StmtExecContext = stmt_E{}
)

type stmt_Q struct {
	*baseStmt
	sQueryer
}

var (
	_ driver.Stmt             = stmt_Q{}
	_ driver.StmtQueryContext = stmt_Q{}
)

type stmt_EQ struct {
	*baseStmt
	sExecer
	sQueryer
}

var (
	_ driver.Stmt             = stmt_EQ{}
	_ driver.StmtExecContext  = stmt_EQ{}
	_ driver.StmtQueryContext = stmt_EQ{}
)

type stmt_C struct {
	*baseStmt
	sColConv
}

var (
	_ driver.Stmt            = stmt_C{}
	_ driver.ColumnConverter = stmt_C{}
)

type stmt_EC struct {
	*baseStmt
	sExecer
	sColConv
}

var (
	_ driver.Stmt            = stmt_EC{}
	_ driver.StmtExecContext = stmt_EC{}
	_ driver.ColumnConverter = stmt_EC{}
)

type stmt_QC struct {
	*baseStmt
	sQueryer
	sColConv
}

var (
	_ driver.Stmt             = stmt_QC{}
	_ driver.StmtQueryContext = stmt_QC{}
	_ driver.ColumnConverter  = stmt_QC{}
)

type stmt_EQC struct {
	*baseStmt
	sExecer
	sQueryer
	sColConv
}

var (
	_ driver.Stmt             = stmt_EQC{}
	_ driver.StmtExecContext  = stmt_EQC{}
	_ driver.StmtQueryContext = stmt_EQC{}
	_ driver.ColumnConverter  = stmt_EQC{}
)

type stmt_N struct {
	*baseStmt
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_N{}
	_ driver.NamedValueChecker = stmt_N{}
)

type stmt_EN struct {
	*baseStmt
	sExecer
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_EN{}
	_ driver.StmtExecContext   = stmt_EN{}
	_ driver.NamedValueChecker = stmt_EN{}
)

type stmt_QN struct {
	*baseStmt
	sQueryer
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_QN{}
	_ driver.StmtQueryContext  = stmt_QN{}
	_ driver.NamedValueChecker = stmt_QN{}
)

type stmt_EQN struct {
	*baseStmt
	sExecer
	sQueryer
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_EQN{}
	_ driver.StmtExecContext   = stmt_EQN{}
	_ driver.StmtQueryContext  = stmt_EQN{}
	_ driver.NamedValueChecker = stmt_EQN{}
)

type stmt_CN struct {
	*baseStmt
	sColConv
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_CN{}
	_ driver.ColumnConverter   = stmt_CN{}
	_ driver.NamedValueChecker = stmt_CN{}
)

type stmt_ECN struct {
	*baseStmt
	sExecer
	sColConv
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_ECN{}
	_ driver.StmtExecContext   = stmt_ECN{}
	_ driver.ColumnConverter   = stmt_ECN{}
	_ driver.NamedValueChecker = stmt_ECN{}
)

type stmt_QCN struct {
	*baseStmt
	sQueryer
	sColConv
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_QCN{}
	_ driver.StmtQueryContext  = stmt_QCN{}
	_ driver.ColumnConverter   = stmt_QCN{}
	_ driver.NamedValueChecker = stmt_QCN{}
)

type stmt_EQCN struct {
	*baseStmt
	sExecer
	sQueryer
	sColConv
	sNVChecker
}

var (
	_ driver.Stmt              = stmt_EQCN{}
	_ driver.StmtExecContext   = stmt_EQCN{}
	_ driver.StmtQueryContext  = stmt_EQCN{}
	_ driver.ColumnConverter   = stmt_EQCN{}
	_ driver.NamedValueChecker = stmt_EQCN{}
)

func wrapStmt(b *baseStmt) driver.Stmt {
	switch stmtFlags(b.inner) {
	case 1:
		return stmt_E{b, sExecer{b}}
	case 2:
		return stmt_Q{b, sQueryer{b}}
	case 3:
		return stmt_EQ{b, sExecer{b}, sQueryer{b}}
	case 4:
		return stmt_C{b, sColConv{b}}
	case 5:
		return stmt_EC{b, sExecer{b}, sColConv{b}}
	case 6:
		return stmt_QC{b, sQueryer{b}, sColConv{b}}
	case 7:
		return stmt_EQC{b, sExecer{b}, sQueryer{b}, sColConv{b}}
	case 8:
		return stmt_N{b, sNVChecker{b}}
	case 9:
		return stmt_EN{b, sExecer{b}, sNVChecker{b}}
	case 10:
		return stmt_QN{b, sQueryer{b}, sNVChecker{b}}
	case 11:
		return stmt_EQN{b, sExecer{b}, sQueryer{b}, sNVChecker{b}}
	case 12:
		return stmt_CN{b, sColConv{b}, sNVChecker{b}}
	case 13:
		return stmt_ECN{b, sExecer{b}, sColConv{b}, sNVChecker{b}}
	case 14:
		return stmt_QCN{b, sQueryer{b}, sColConv{b}, sNVChecker{b}}
	case 15:
		return stmt_EQCN{b, sExecer{b}, sQueryer{b}, sColConv{b}, sNVChecker{b}}
	default:
		return b
	}
}
