apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-postgresql
  labels:
{{ include "hotload-integration-tests.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
{{ include "hotload-integration-tests.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: postgresql
{{ include "hotload-integration-tests.selectorLabels" . | indent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-postgres-secret
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          {{- if not .Values.postgres.persistence.enabled }}
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U {{ .Values.postgres.user }} -d {{ .Values.postgres.database }} -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U {{ .Values.postgres.user }} -d {{ .Values.postgres.database }} -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
      volumes:
        - name: initdb
          configMap:
            name: {{ .Values.name }}-postgres-initdb
        {{- if not .Values.postgres.persistence.enabled }}
        - name: postgres-data
          emptyDir: {}
        {{- end }}