apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-postgres-initdb
  labels:
{{ include "hotload-integration-tests.labels" . | indent 4 }}
data:
  init.sql: {{ .Values.postgres.initScript | quote }}