apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-postgres-secret
  labels:
{{ include "hotload-integration-tests.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | b64enc | quote }}
  postgres-password: {{ .Values.postgres.postgresPassword | b64enc | quote }}