// Code generated by internal/gen. DO NOT EDIT.

package dbfake

import "database/sql/driver"

type fconn_bare struct {
	fvBase
}

type fconn_e struct {
	fvBase
	fvExecer
}

type fconn_E struct {
	fvBase
	fvExecerCtx
}

type fconn_eE struct {
	fvBase
	fvExecer
	fvExecerCtx
}

type fconn_q struct {
	fvBase
	fvQueryer
}

type fconn_eq struct {
	fvBase
	fvExecer
	fvQueryer
}

type fconn_Eq struct {
	fvBase
	fvExecerCtx
	fvQueryer
}

type fconn_eEq struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
}

type fconn_Q struct {
	fvBase
	fvQueryerCtx
}

type fconn_eQ struct {
	fvBase
	fvExecer
	fvQueryerCtx
}

type fconn_EQ struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
}

type fconn_eEQ struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
}

type fconn_qQ struct {
	fvBase
	fvQueryer
	fvQueryerCtx
}

type fconn_eqQ struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
}

type fconn_EqQ struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
}

type fconn_eEqQ struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
}

type fconn_P struct {
	fvBase
	fvPinger
}

type fconn_eP struct {
	fvBase
	fvExecer
	fvPinger
}

type fconn_EP struct {
	fvBase
	fvExecerCtx
	fvPinger
}

type fconn_eEP struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvPinger
}

type fconn_qP struct {
	fvBase
	fvQueryer
	fvPinger
}

type fconn_eqP struct {
	fvBase
	fvExecer
	fvQueryer
	fvPinger
}

type fconn_EqP struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvPinger
}

type fconn_eEqP struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvPinger
}

type fconn_QP struct {
	fvBase
	fvQueryerCtx
	fvPinger
}

type fconn_eQP struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvPinger
}

type fconn_EQP struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvPinger
}

type fconn_eEQP struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvPinger
}

type fconn_qQP struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvPinger
}

type fconn_eqQP struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvPinger
}

type fconn_EqQP struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
}

type fconn_eEqQP struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
}

type fconn_N struct {
	fvBase
	fvNVChecker
}

type fconn_eN struct {
	fvBase
	fvExecer
	fvNVChecker
}

type fconn_EN struct {
	fvBase
	fvExecerCtx
	fvNVChecker
}

type fconn_eEN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvNVChecker
}

type fconn_qN struct {
	fvBase
	fvQueryer
	fvNVChecker
}

type fconn_eqN struct {
	fvBase
	fvExecer
	fvQueryer
	fvNVChecker
}

type fconn_EqN struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvNVChecker
}

type fconn_eEqN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvNVChecker
}

type fconn_QN struct {
	fvBase
	fvQueryerCtx
	fvNVChecker
}

type fconn_eQN struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvNVChecker
}

type fconn_EQN struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvNVChecker
}

type fconn_eEQN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvNVChecker
}

type fconn_qQN struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvNVChecker
}

type fconn_eqQN struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvNVChecker
}

type fconn_EqQN struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvNVChecker
}

type fconn_eEqQN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvNVChecker
}

type fconn_PN struct {
	fvBase
	fvPinger
	fvNVChecker
}

type fconn_ePN struct {
	fvBase
	fvExecer
	fvPinger
	fvNVChecker
}

type fconn_EPN struct {
	fvBase
	fvExecerCtx
	fvPinger
	fvNVChecker
}

type fconn_eEPN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvPinger
	fvNVChecker
}

type fconn_qPN struct {
	fvBase
	fvQueryer
	fvPinger
	fvNVChecker
}

type fconn_eqPN struct {
	fvBase
	fvExecer
	fvQueryer
	fvPinger
	fvNVChecker
}

type fconn_EqPN struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvPinger
	fvNVChecker
}

type fconn_eEqPN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvPinger
	fvNVChecker
}

type fconn_QPN struct {
	fvBase
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_eQPN struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_EQPN struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_eEQPN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_qQPN struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_eqQPN struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_EqQPN struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_eEqQPN struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
}

type fconn_A struct {
	fvBase
	fvClassA
}

type fconn_eA struct {
	fvBase
	fvExecer
	fvClassA
}

type fconn_EA struct {
	fvBase
	fvExecerCtx
	fvClassA
}

type fconn_eEA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvClassA
}

type fconn_qA struct {
	fvBase
	fvQueryer
	fvClassA
}

type fconn_eqA struct {
	fvBase
	fvExecer
	fvQueryer
	fvClassA
}

type fconn_EqA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvClassA
}

type fconn_eEqA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvClassA
}

type fconn_QA struct {
	fvBase
	fvQueryerCtx
	fvClassA
}

type fconn_eQA struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvClassA
}

type fconn_EQA struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvClassA
}

type fconn_eEQA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvClassA
}

type fconn_qQA struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvClassA
}

type fconn_eqQA struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvClassA
}

type fconn_EqQA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvClassA
}

type fconn_eEqQA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvClassA
}

type fconn_PA struct {
	fvBase
	fvPinger
	fvClassA
}

type fconn_ePA struct {
	fvBase
	fvExecer
	fvPinger
	fvClassA
}

type fconn_EPA struct {
	fvBase
	fvExecerCtx
	fvPinger
	fvClassA
}

type fconn_eEPA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvPinger
	fvClassA
}

type fconn_qPA struct {
	fvBase
	fvQueryer
	fvPinger
	fvClassA
}

type fconn_eqPA struct {
	fvBase
	fvExecer
	fvQueryer
	fvPinger
	fvClassA
}

type fconn_EqPA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvPinger
	fvClassA
}

type fconn_eEqPA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvPinger
	fvClassA
}

type fconn_QPA struct {
	fvBase
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_eQPA struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_EQPA struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_eEQPA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_qQPA struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_eqQPA struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_EqQPA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_eEqQPA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvClassA
}

type fconn_NA struct {
	fvBase
	fvNVChecker
	fvClassA
}

type fconn_eNA struct {
	fvBase
	fvExecer
	fvNVChecker
	fvClassA
}

type fconn_ENA struct {
	fvBase
	fvExecerCtx
	fvNVChecker
	fvClassA
}

type fconn_eENA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvNVChecker
	fvClassA
}

type fconn_qNA struct {
	fvBase
	fvQueryer
	fvNVChecker
	fvClassA
}

type fconn_eqNA struct {
	fvBase
	fvExecer
	fvQueryer
	fvNVChecker
	fvClassA
}

type fconn_EqNA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvNVChecker
	fvClassA
}

type fconn_eEqNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvNVChecker
	fvClassA
}

type fconn_QNA struct {
	fvBase
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_eQNA struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_EQNA struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_eEQNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_qQNA struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_eqQNA struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_EqQNA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_eEqQNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvNVChecker
	fvClassA
}

type fconn_PNA struct {
	fvBase
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_ePNA struct {
	fvBase
	fvExecer
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_EPNA struct {
	fvBase
	fvExecerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eEPNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_qPNA struct {
	fvBase
	fvQueryer
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eqPNA struct {
	fvBase
	fvExecer
	fvQueryer
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_EqPNA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eEqPNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_QPNA struct {
	fvBase
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eQPNA struct {
	fvBase
	fvExecer
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_EQPNA struct {
	fvBase
	fvExecerCtx
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eEQPNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_qQPNA struct {
	fvBase
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eqQPNA struct {
	fvBase
	fvExecer
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_EqQPNA struct {
	fvBase
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fconn_eEqQPNA struct {
	fvBase
	fvExecer
	fvExecerCtx
	fvQueryer
	fvQueryerCtx
	fvPinger
	fvNVChecker
	fvClassA
}

type fstmt_bare struct {
	fsBase
}

type fstmt_E struct {
	fsBase
	fsExecerCtx
}

type fstmt_Q struct {
	fsBase
	fsQueryerCtx
}

type fstmt_EQ struct {
	fsBase
	fsExecerCtx
	fsQueryerCtx
}

type fstmt_C struct {
	fsBase
	fsColConv
}

type fstmt_EC struct {
	fsBase
	fsExecerCtx
	fsColConv
}

type fstmt_QC struct {
	fsBase
	fsQueryerCtx
	fsColConv
}

type fstmt_EQC struct {
	fsBase
	fsExecerCtx
	fsQueryerCtx
	fsColConv
}

type fstmt_N struct {
	fsBase
	fsNVChecker
}

type fstmt_EN struct {
	fsBase
	fsExecerCtx
	fsNVChecker
}

type fstmt_QN struct {
	fsBase
	fsQueryerCtx
	fsNVChecker
}

type fstmt_EQN struct {
	fsBase
	fsExecerCtx
	fsQueryerCtx
	fsNVChecker
}

type fstmt_CN struct {
	fsBase
	fsColConv
	fsNVChecker
}

type fstmt_ECN struct {
	fsBase
	fsExecerCtx
	fsColConv
	fsNVChecker
}

type fstmt_QCN struct {
	fsBase
	fsQueryerCtx
	fsColConv
	fsNVChecker
}

type fstmt_EQCN struct {
	fsBase
	fsExecerCtx
	fsQueryerCtx
	fsColConv
	fsNVChecker
}

// viewConn returns c behind a view exposing exactly the optional
// interfaces selected by c.caps. The four interfaces hotload always
// synthesizes (ConnPrepareContext, ConnBeginTx, SessionResetter,
// Validator) are grouped: if any of their caps is set the view exposes
// all four.
func viewConn(c *Conn) driver.Conn {
	var f int
	if c.caps&CapExecer != 0 {
		f |= 1 << 0
	}
	if c.caps&CapExecerContext != 0 {
		f |= 1 << 1
	}
	if c.caps&CapQueryer != 0 {
		f |= 1 << 2
	}
	if c.caps&CapQueryerContext != 0 {
		f |= 1 << 3
	}
	if c.caps&CapPinger != 0 {
		f |= 1 << 4
	}
	if c.caps&CapNamedValueChecker != 0 {
		f |= 1 << 5
	}
	if c.caps&(CapConnPrepareContext|CapConnBeginTx|CapSessionResetter|CapValidator) != 0 {
		f |= 1 << 6
	}
	switch f {
	case 0:
		return fconn_bare{fvBase{c}}
	case 1:
		return fconn_e{fvBase{c}, fvExecer{c}}
	case 2:
		return fconn_E{fvBase{c}, fvExecerCtx{c}}
	case 3:
		return fconn_eE{fvBase{c}, fvExecer{c}, fvExecerCtx{c}}
	case 4:
		return fconn_q{fvBase{c}, fvQueryer{c}}
	case 5:
		return fconn_eq{fvBase{c}, fvExecer{c}, fvQueryer{c}}
	case 6:
		return fconn_Eq{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}}
	case 7:
		return fconn_eEq{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}}
	case 8:
		return fconn_Q{fvBase{c}, fvQueryerCtx{c}}
	case 9:
		return fconn_eQ{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}}
	case 10:
		return fconn_EQ{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}}
	case 11:
		return fconn_eEQ{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}}
	case 12:
		return fconn_qQ{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}}
	case 13:
		return fconn_eqQ{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}}
	case 14:
		return fconn_EqQ{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}}
	case 15:
		return fconn_eEqQ{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}}
	case 16:
		return fconn_P{fvBase{c}, fvPinger{c}}
	case 17:
		return fconn_eP{fvBase{c}, fvExecer{c}, fvPinger{c}}
	case 18:
		return fconn_EP{fvBase{c}, fvExecerCtx{c}, fvPinger{c}}
	case 19:
		return fconn_eEP{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvPinger{c}}
	case 20:
		return fconn_qP{fvBase{c}, fvQueryer{c}, fvPinger{c}}
	case 21:
		return fconn_eqP{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvPinger{c}}
	case 22:
		return fconn_EqP{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}}
	case 23:
		return fconn_eEqP{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}}
	case 24:
		return fconn_QP{fvBase{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 25:
		return fconn_eQP{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 26:
		return fconn_EQP{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 27:
		return fconn_eEQP{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 28:
		return fconn_qQP{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 29:
		return fconn_eqQP{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 30:
		return fconn_EqQP{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 31:
		return fconn_eEqQP{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}}
	case 32:
		return fconn_N{fvBase{c}, fvNVChecker{c}}
	case 33:
		return fconn_eN{fvBase{c}, fvExecer{c}, fvNVChecker{c}}
	case 34:
		return fconn_EN{fvBase{c}, fvExecerCtx{c}, fvNVChecker{c}}
	case 35:
		return fconn_eEN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvNVChecker{c}}
	case 36:
		return fconn_qN{fvBase{c}, fvQueryer{c}, fvNVChecker{c}}
	case 37:
		return fconn_eqN{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvNVChecker{c}}
	case 38:
		return fconn_EqN{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvNVChecker{c}}
	case 39:
		return fconn_eEqN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvNVChecker{c}}
	case 40:
		return fconn_QN{fvBase{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 41:
		return fconn_eQN{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 42:
		return fconn_EQN{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 43:
		return fconn_eEQN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 44:
		return fconn_qQN{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 45:
		return fconn_eqQN{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 46:
		return fconn_EqQN{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 47:
		return fconn_eEqQN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}}
	case 48:
		return fconn_PN{fvBase{c}, fvPinger{c}, fvNVChecker{c}}
	case 49:
		return fconn_ePN{fvBase{c}, fvExecer{c}, fvPinger{c}, fvNVChecker{c}}
	case 50:
		return fconn_EPN{fvBase{c}, fvExecerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 51:
		return fconn_eEPN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 52:
		return fconn_qPN{fvBase{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}}
	case 53:
		return fconn_eqPN{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}}
	case 54:
		return fconn_EqPN{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}}
	case 55:
		return fconn_eEqPN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}}
	case 56:
		return fconn_QPN{fvBase{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 57:
		return fconn_eQPN{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 58:
		return fconn_EQPN{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 59:
		return fconn_eEQPN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 60:
		return fconn_qQPN{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 61:
		return fconn_eqQPN{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 62:
		return fconn_EqQPN{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 63:
		return fconn_eEqQPN{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}}
	case 64:
		return fconn_A{fvBase{c}, fvClassA{c}}
	case 65:
		return fconn_eA{fvBase{c}, fvExecer{c}, fvClassA{c}}
	case 66:
		return fconn_EA{fvBase{c}, fvExecerCtx{c}, fvClassA{c}}
	case 67:
		return fconn_eEA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvClassA{c}}
	case 68:
		return fconn_qA{fvBase{c}, fvQueryer{c}, fvClassA{c}}
	case 69:
		return fconn_eqA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvClassA{c}}
	case 70:
		return fconn_EqA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvClassA{c}}
	case 71:
		return fconn_eEqA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvClassA{c}}
	case 72:
		return fconn_QA{fvBase{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 73:
		return fconn_eQA{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 74:
		return fconn_EQA{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 75:
		return fconn_eEQA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 76:
		return fconn_qQA{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 77:
		return fconn_eqQA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 78:
		return fconn_EqQA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 79:
		return fconn_eEqQA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvClassA{c}}
	case 80:
		return fconn_PA{fvBase{c}, fvPinger{c}, fvClassA{c}}
	case 81:
		return fconn_ePA{fvBase{c}, fvExecer{c}, fvPinger{c}, fvClassA{c}}
	case 82:
		return fconn_EPA{fvBase{c}, fvExecerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 83:
		return fconn_eEPA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 84:
		return fconn_qPA{fvBase{c}, fvQueryer{c}, fvPinger{c}, fvClassA{c}}
	case 85:
		return fconn_eqPA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvPinger{c}, fvClassA{c}}
	case 86:
		return fconn_EqPA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}, fvClassA{c}}
	case 87:
		return fconn_eEqPA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}, fvClassA{c}}
	case 88:
		return fconn_QPA{fvBase{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 89:
		return fconn_eQPA{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 90:
		return fconn_EQPA{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 91:
		return fconn_eEQPA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 92:
		return fconn_qQPA{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 93:
		return fconn_eqQPA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 94:
		return fconn_EqQPA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 95:
		return fconn_eEqQPA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvClassA{c}}
	case 96:
		return fconn_NA{fvBase{c}, fvNVChecker{c}, fvClassA{c}}
	case 97:
		return fconn_eNA{fvBase{c}, fvExecer{c}, fvNVChecker{c}, fvClassA{c}}
	case 98:
		return fconn_ENA{fvBase{c}, fvExecerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 99:
		return fconn_eENA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 100:
		return fconn_qNA{fvBase{c}, fvQueryer{c}, fvNVChecker{c}, fvClassA{c}}
	case 101:
		return fconn_eqNA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvNVChecker{c}, fvClassA{c}}
	case 102:
		return fconn_EqNA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvNVChecker{c}, fvClassA{c}}
	case 103:
		return fconn_eEqNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvNVChecker{c}, fvClassA{c}}
	case 104:
		return fconn_QNA{fvBase{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 105:
		return fconn_eQNA{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 106:
		return fconn_EQNA{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 107:
		return fconn_eEQNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 108:
		return fconn_qQNA{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 109:
		return fconn_eqQNA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 110:
		return fconn_EqQNA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 111:
		return fconn_eEqQNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvNVChecker{c}, fvClassA{c}}
	case 112:
		return fconn_PNA{fvBase{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 113:
		return fconn_ePNA{fvBase{c}, fvExecer{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 114:
		return fconn_EPNA{fvBase{c}, fvExecerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 115:
		return fconn_eEPNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 116:
		return fconn_qPNA{fvBase{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 117:
		return fconn_eqPNA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 118:
		return fconn_EqPNA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 119:
		return fconn_eEqPNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 120:
		return fconn_QPNA{fvBase{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 121:
		return fconn_eQPNA{fvBase{c}, fvExecer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 122:
		return fconn_EQPNA{fvBase{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 123:
		return fconn_eEQPNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 124:
		return fconn_qQPNA{fvBase{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 125:
		return fconn_eqQPNA{fvBase{c}, fvExecer{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 126:
		return fconn_EqQPNA{fvBase{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	case 127:
		return fconn_eEqQPNA{fvBase{c}, fvExecer{c}, fvExecerCtx{c}, fvQueryer{c}, fvQueryerCtx{c}, fvPinger{c}, fvNVChecker{c}, fvClassA{c}}
	}
	panic("unreachable")
}

// viewStmt returns s behind a view exposing exactly the optional stmt
// interfaces selected by the conn's caps.
func viewStmt(s *Stmt) driver.Stmt {
	var f int
	if s.conn.caps&CapStmtExecContext != 0 {
		f |= 1 << 0
	}
	if s.conn.caps&CapStmtQueryContext != 0 {
		f |= 1 << 1
	}
	if s.conn.caps&CapColumnConverter != 0 {
		f |= 1 << 2
	}
	if s.conn.caps&CapStmtNamedValueChecker != 0 {
		f |= 1 << 3
	}
	switch f {
	case 0:
		return fstmt_bare{fsBase{s}}
	case 1:
		return fstmt_E{fsBase{s}, fsExecerCtx{s}}
	case 2:
		return fstmt_Q{fsBase{s}, fsQueryerCtx{s}}
	case 3:
		return fstmt_EQ{fsBase{s}, fsExecerCtx{s}, fsQueryerCtx{s}}
	case 4:
		return fstmt_C{fsBase{s}, fsColConv{s}}
	case 5:
		return fstmt_EC{fsBase{s}, fsExecerCtx{s}, fsColConv{s}}
	case 6:
		return fstmt_QC{fsBase{s}, fsQueryerCtx{s}, fsColConv{s}}
	case 7:
		return fstmt_EQC{fsBase{s}, fsExecerCtx{s}, fsQueryerCtx{s}, fsColConv{s}}
	case 8:
		return fstmt_N{fsBase{s}, fsNVChecker{s}}
	case 9:
		return fstmt_EN{fsBase{s}, fsExecerCtx{s}, fsNVChecker{s}}
	case 10:
		return fstmt_QN{fsBase{s}, fsQueryerCtx{s}, fsNVChecker{s}}
	case 11:
		return fstmt_EQN{fsBase{s}, fsExecerCtx{s}, fsQueryerCtx{s}, fsNVChecker{s}}
	case 12:
		return fstmt_CN{fsBase{s}, fsColConv{s}, fsNVChecker{s}}
	case 13:
		return fstmt_ECN{fsBase{s}, fsExecerCtx{s}, fsColConv{s}, fsNVChecker{s}}
	case 14:
		return fstmt_QCN{fsBase{s}, fsQueryerCtx{s}, fsColConv{s}, fsNVChecker{s}}
	case 15:
		return fstmt_EQCN{fsBase{s}, fsExecerCtx{s}, fsQueryerCtx{s}, fsColConv{s}, fsNVChecker{s}}
	}
	panic("unreachable")
}
